#!/usr/bin/env ansible-playbook
---
- name: Install SOPS
  hosts: localhost
  gather_facts: false
  become: true
  become_user: root
  tasks:
    - name: Apply the SOPS installer community role
      ansible.builtin.include_role:
        name: community.sops.install
      vars:
        sops_version: 3.10.2
        sops_install_on_localhost: true
