---
name: Destroy existing crc cluster

on:
  workflow_dispatch:

env:
  SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Connect to WARP
        uses: Boostport/setup-cloudflare-warp@v1
        with:
          organization: makeitworkcloud
          auth_client_id: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_ID }}
          auth_client_secret: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_SECRET }}

      - name: Setup SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >private_key.pem
          chmod 600 private_key.pem

      - name: Stop & Destroy cluster
        run: |
          ssh -i private_key.pem ltc.makeitwork.cloud crc stop -f
          ssh -i private_key.pem ltc.makeitwork.cloud crc delete -f

